name: Ruby
variants:

  - id: script
    name: Simple Ruby Script
    description: Dockerfile Generator for basic Ruby scripts and apps without any specific framework
    files:
      - dockerfile
      - dockerignore
    variables:
      - name:  'RUBY_VERSION'
        value: '3.2.0'
      - name:  'APP_NAME'
        value: 'my_app'
      - name:  'ENTRYPOINT'
        value: 'main.rb'

  - id: sinatra
    name: Sinatra Web App
    description: Dockerize Sinatra or Rack web applications in Ruby
    files:
      - dockerfile
      - dockerignore
    variables:
      - name:  'RUBY_VERSION'
        value: '3.2.0'
      - name:  'DEFAULT_ENV'
        value: 'production'
      - name:  'PORT'
        value: '4567'
      - name:  'APP_NAME'
        value: 'app'

