name: Python
variants:

  - id: script
    name: Simple Python Script
    description: Dockerfile Generator for basic Python scripts and apps without any specific framework
    files:
      - dockerfile
      - dockerignore
    variables:
      - name:  'PYTHON_VERSION'
        value: '3.10'
      - name:  'REQUIREMENTS_FILE'
        value: 'requirements.txt'
      - name:  'APP_NAME'
        value: 'my_app'
      - name:  'ENTRYPOINT'
        value: 'script.py'

  - id: flask
    name: Flask Web App
    description: Dockerfile Generator for web applications built with Flask
    files:
      - dockerfile
      - dockerignore
    variables:
      - name:  'PYTHON_VERSION'
        value: '3.10'
      - name:  'DEFAULT_ENV'
        value: 'production'
      - name:  'REQUIREMENTS_FILE'
        value: 'requirements.txt'
      - name:  'PORT'
        value: '5000'
      - name:  'APP_NAME'
        value: 'app'

